import { User, Vehicle, Booking, MaintenanceItem, RepairOrder, ThemeOption, GPSTrackingInfo, Department, Driver, MasterLocationPurpose } from '../types';

export const THEMES_LIST: ThemeOption[] = [
  { id: 'theme-frosted-glass', name: 'Frosted Glass ✨', desc: 'กระจกฝ้าพรีเมียม คริสตัล', colors: ['#0ea5e9', '#f0f9ff', '#6366f1'] },
  { id: 'theme-crimson-3d', name: 'Crimson 3D', desc: 'แดง-ขาว 3D เงางาม', colors: ['#ff2a4b', '#ffffff', '#b3001b'] },
  { id: 'theme-cyberpunk-3d', name: 'Neon Cyberpunk', desc: 'ฟ้า-น้ำเงิน ไซเบอร์', colors: ['#00f2fe', '#0b1329', '#38bdf8'], isDark: true },
  { id: 'theme-solar-sunset', name: 'Solar Sunset', desc: 'ส้ม-ชมพู อบอุ่น', colors: ['#ff5200', '#fff8f0', '#ff1168'] },
  { id: 'theme-berry-blossom', name: 'Berry Blossom', desc: 'ชมพู-บับเบิลกัม', colors: ['#ec4899', '#fdf2f9', '#8b5cf6'] },
  { id: 'theme-royal-velvet', name: 'Royal Velvet', desc: 'ม่วง-อเมทิสต์ หรูหรา', colors: ['#7c3aed', '#f6f0fd', '#c084fc'] },
  { id: 'theme-emerald-glow', name: 'Emerald Glow', desc: 'เขียวมรกต-มิ้นต์', colors: ['#10b981', '#f0fdf4', '#047857'] },
  { id: 'theme-ocean-breeze', name: 'Ocean Breeze', desc: 'ฟ้าทะเล คลีนสดชื่น', colors: ['#0284c7', '#f0f9ff', '#2563eb'] },
  { id: 'theme-gold-obsidian', name: 'Gold & Obsidian', desc: 'ทอง-ดำ พรีเมียม', colors: ['#eab308', '#0f172a', '#fde047'], isDark: true },
  { id: 'theme-pastel-holo', name: 'Pastel Holo', desc: 'โฮโลแกรม หลากสี', colors: ['#f472b6', '#38bdf8', '#a7f3d0'] },
  { id: 'theme-industrial-steel', name: 'Industrial Steel', desc: 'เทาโครเมียม เมทัลลิก', colors: ['#4b5563', '#f3f4f6', '#111827'] },
  { id: 'theme-oriental-crimson', name: 'Oriental Crimson ⭐', desc: 'แดงชาด-ทอง มงคล', colors: ['#d90429', '#fff5f6', '#ffb703'] },
  { id: 'theme-violet-midnight', name: 'Violet Midnight ⭐', desc: 'ม่วงคราม ออโรร่า', colors: ['#6366f1', '#090514', '#10b981'], isDark: true }
];

export const INITIAL_DEPARTMENTS: Department[] = [
  { id: 'dept-1', code: 'DEPT-SUPPORT', name: 'ฝ่ายสนับสนุน', managerName: 'วิภา สุขสม', contactPhone: '02-123-4501', description: 'ดูแลระบบ IT, ซัพพอร์ต และโครงสร้างพื้นฐาน' },
  { id: 'dept-2', code: 'DEPT-ADMIN', name: 'ฝ่ายบริหาร', managerName: 'วิภา สุขสม', contactPhone: '02-123-4502', description: 'บริหารจัดการทั่วไป ธุรการ และยานพาหนะ' },
  { id: 'dept-3', code: 'DEPT-EXEC', name: 'ผู้บริหาร', managerName: 'ประยุทธ์ เจริญสุข', contactPhone: '02-123-4500', description: 'คณะกรรมการบริหารและผู้อำนวยการ' },
  { id: 'dept-4', code: 'DEPT-FLEET', name: 'ฝ่ายยานพาหนะ', managerName: 'สมศักดิ์ ขับดี', contactPhone: '02-123-4504', description: 'บริหารกองยานพาหนะและการเดินทาง' },
  { id: 'dept-5', code: 'DEPT-FINANCE', name: 'ฝ่ายการเงิน', managerName: 'นภาพร รักงาน', contactPhone: '02-123-4505', description: 'บัญชี การเงิน และจัดซื้อ' },
  { id: 'dept-6', code: 'DEPT-DEV', name: 'ฝ่ายพัฒนา', managerName: 'ปิยะ ตั้งใจ', contactPhone: '02-123-4506', description: 'วิจัย พัฒนาซอฟต์แวร์ และนวัตกรรม' },
  { id: 'dept-7', code: 'DEPT-SALES', name: 'ฝ่ายขายและการตลาด', managerName: 'ธนากร มั่งมี', contactPhone: '02-123-4507', description: 'งานขาย ประสานงานลูกค้า และคู่ค้า OGA' },
];

export const INITIAL_DRIVERS: Driver[] = [
  { id: 'drv-1', name: 'สมศักดิ์ ขับดี', phone: '084-999-3344', licenseNumber: 'DL-66-889912', licenseExpiry: '31/12/2572', status: 'available', rating: 4.9, experienceYears: 12, avatar: 'ส' },
  { id: 'drv-2', name: 'มานะ ปลอดภัย', phone: '089-112-3344', licenseNumber: 'DL-65-774411', licenseExpiry: '15/08/2571', status: 'available', rating: 4.8, experienceYears: 8, avatar: 'ม' },
  { id: 'drv-3', name: 'ชาติชาย ว่องไว', phone: '081-554-6677', licenseNumber: 'DL-64-112233', licenseExpiry: '20/05/2570', status: 'on_trip', rating: 4.7, experienceYears: 15, avatar: 'ช' },
];

export const INITIAL_MASTER_ITEMS: MasterLocationPurpose[] = [
  { id: 'loc-1', category: 'destination', name: 'สำนักงานใหญ่ OGA (กรุงเทพฯ)', description: 'อาคารสำนักงานใหญ่ สาทร', popular: true },
  { id: 'loc-2', category: 'destination', name: 'นิคมอุตสาหกรรมนวนคร จ.ปทุมธานี', description: 'โรงงานคู่ค้าและคลังสินค้า', popular: true },
  { id: 'loc-3', category: 'destination', name: 'นิคมอุตสาหกรรมอมตะซิตี้ จ.ชลบุรี', description: 'ศูนย์จัดส่งและโรงงานภาคตะวันออก', popular: true },
  { id: 'loc-4', category: 'destination', name: 'สนามบินสุวรรณภูมิ', description: 'รับ-ส่งผู้บริหารและลูกค้าต่างประเทศ', popular: true },
  { id: 'loc-5', category: 'destination', name: 'ศูนย์ประชุมแห่งชาติสิริกิติ์', description: 'งานสัมมนาและนิทรรศการ OGA Expo', popular: false },
  { id: 'pur-1', category: 'purpose', name: 'ติดต่อประสานงานโครงการ OGA Partner', description: 'งานประชุมและประสานงานธุรกิจ', popular: true },
  { id: 'pur-2', category: 'purpose', name: 'ส่งมอบสินค้าและอุปกรณ์ฮาร์ดแวร์', description: 'ขนส่งอุปกรณ์ให้กับลูกค้า', popular: true },
  { id: 'pur-3', category: 'purpose', name: 'รับ-ส่งคณะผู้บริหาร / ลูกค้าคนสำคัญ (VIP)', description: 'การเดินทางสำหรับผู้บริหารและแขก', popular: true },
  { id: 'pur-4', category: 'purpose', name: 'เข้าร่วมงานสัมมนาและฝึกอบรมภายนอก', description: 'อบรมพัฒนาทักษะวิชาชีพ', popular: false },
  { id: 'pur-5', category: 'purpose', name: 'ตรวจเช็คไซต์งานและบำรุงรักษาหน้างาน', description: 'บริการซ่อมและบำรุงรักษา Onsite', popular: true },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'u-1',
    employeeId: 'OGA-1001',
    name: 'สมชาย ใจดี',
    department: 'ฝ่ายสนับสนุน',
    role: 'admin',
    roleLabel: 'ผู้ดูแลระบบ',
    avatar: 'ส',
    email: 'somchai.j@ogainternational.com',
    phone: '081-234-5678',
    drivingLicenseNo: 'DL-62-102938',
    drivingLicenseExpiry: '15/09/2571',
    status: 'active',
  },
  {
    id: 'u-2',
    employeeId: 'OGA-1002',
    name: 'วิภา สุขสม',
    department: 'ฝ่ายบริหาร',
    role: 'approver1',
    roleLabel: 'หัวหน้า',
    avatar: 'ว',
    email: 'wipha.s@ogainternational.com',
    phone: '089-876-5432',
    drivingLicenseNo: 'DL-64-554433',
    drivingLicenseExpiry: '30/11/2570',
    status: 'active',
  },
  {
    id: 'u-3',
    employeeId: 'OGA-1003',
    name: 'ประยุทธ์ เจริญสุข',
    department: 'ผู้บริหาร',
    role: 'approver2',
    roleLabel: 'ผู้อำนวยการ',
    avatar: 'ป',
    email: 'prayut.c@ogainternational.com',
    phone: '086-555-1122',
    drivingLicenseNo: 'DL-59-998877',
    drivingLicenseExpiry: '25/03/2573',
    status: 'active',
  },
  {
    id: 'u-4',
    employeeId: 'OGA-1004',
    name: 'สมศักดิ์ ขับดี',
    department: 'ฝ่ายยานพาหนะ',
    role: 'driver',
    roleLabel: 'พนักงานขับรถ',
    avatar: 'ส',
    email: 'somsak.k@ogainternational.com',
    phone: '084-999-3344',
    drivingLicenseNo: 'DL-66-889912',
    drivingLicenseExpiry: '31/12/2572',
    status: 'active',
  },
  {
    id: 'u-5',
    employeeId: 'OGA-1005',
    name: 'นภาพร รักงาน',
    department: 'ฝ่ายการเงิน',
    role: 'user',
    roleLabel: 'ผู้ใช้งาน',
    avatar: 'น',
    email: 'napaporn.r@ogainternational.com',
    phone: '082-111-2233',
    drivingLicenseNo: 'DL-65-332211',
    drivingLicenseExpiry: '10/06/2571',
    status: 'active',
  },
  {
    id: 'u-6',
    employeeId: 'OGA-1006',
    name: 'ปิยะ ตั้งใจ',
    department: 'ฝ่ายพัฒนา',
    role: 'user',
    roleLabel: 'ผู้ใช้งาน',
    avatar: 'ป',
    email: 'piya.t@ogainternational.com',
    phone: '085-777-8899',
    drivingLicenseNo: 'DL-67-123456',
    drivingLicenseExpiry: '05/01/2572',
    status: 'active',
  },
  {
    id: 'u-7',
    employeeId: 'OGA-1007',
    name: 'ธนากร มั่งมี',
    department: 'ฝ่ายขายและการตลาด',
    role: 'user',
    roleLabel: 'ผู้ใช้งาน',
    avatar: 'ธ',
    email: 'thanakorn.m@ogainternational.com',
    phone: '083-445-6677',
    drivingLicenseNo: 'DL-66-990011',
    drivingLicenseExpiry: '19/08/2572',
    status: 'active',
  },
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'v-1',
    name: 'Toyota Camry',
    type: 'รถเก๋ง',
    plate: 'กข 1234 กทม.',
    seats: 5,
    fuelType: 'เบนซิน + แก๊ส LPG (2 เชื้อเพลิง)',
    mileage: 45230,
    color: 'ขาวมุก',
    image: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=600&auto=format&fit=crop&q=80',
    insuranceExpiry: '15/08/2570',
    taxExpiry: '31/12/2570',
    inspectionExpiry: '20/06/2570',
    gasCertExpiry: '15/10/2570',
    gasTankExpiry: '20/12/2575',
    status: 'available',
    currentLocation: 'ลานจอด OGA สำนักงานใหญ่',
    lat: 13.7563,
    lng: 100.5018,
  },
  {
    id: 'v-2',
    name: 'Toyota Fortuner',
    type: 'รถ SUV',
    plate: 'ขค 5678 กทม.',
    seats: 7,
    fuelType: 'ดีเซล + แก๊ส (2 เชื้อเพลิง)',
    mileage: 78540,
    color: 'ดำ',
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=600&auto=format&fit=crop&q=80',
    insuranceExpiry: '20/03/2570',
    taxExpiry: '31/12/2570',
    inspectionExpiry: '10/04/2570',
    gasCertExpiry: '10/04/2570',
    gasTankExpiry: '15/08/2576',
    status: 'in_use',
    currentLocation: 'จ.ปทุมธานี (กำลังเดินทาง)',
    lat: 14.0205,
    lng: 100.5284,
  },
  {
    id: 'v-3',
    name: 'Toyota Vios 4470',
    type: 'รถเก๋ง',
    plate: 'ฆพ 4470 กทม.',
    seats: 5,
    fuelType: 'เบนซิน + แก๊ส LPG (2 เชื้อเพลิง)',
    mileage: 32100,
    color: 'ขาวมุก',
    image: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=600&auto=format&fit=crop&q=80',
    insuranceExpiry: '30/11/2570',
    taxExpiry: '31/12/2570',
    inspectionExpiry: '15/01/2571',
    gasCertExpiry: '25/11/2570',
    gasTankExpiry: '10/05/2577',
    status: 'available',
    currentLocation: 'ลานจอด OGA สำนักงานใหญ่',
    lat: 13.7563,
    lng: 100.5018,
  },
  {
    id: 'v-4',
    name: 'Toyota Hilux Revo',
    type: 'รถกระบะ',
    plate: 'ฉช 3344 กทม.',
    seats: 5,
    fuelType: 'ดีเซล',
    mileage: 91200,
    color: 'แดง',
    image: 'https://images.unsplash.com/photo-1559416523-140ddc3d238c?w=600&auto=format&fit=crop&q=80',
    insuranceExpiry: '10/05/2570',
    taxExpiry: '31/12/2570',
    inspectionExpiry: '25/03/2570',
    status: 'maintenance',
    currentLocation: 'ศูนย์บริการโตโยต้า สาทร',
    lat: 13.8282,
    lng: 100.5583,
  },
  {
    id: 'v-5',
    name: 'Toyota Vios 2108',
    type: 'รถเก๋ง',
    plate: 'ฆค 2108 กทม.',
    seats: 5,
    fuelType: 'เบนซิน + แก๊ส LPG (2 เชื้อเพลิง)',
    mileage: 124300,
    color: 'ขาวมุก',
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=600&auto=format&fit=crop&q=80',
    insuranceExpiry: '05/09/2570',
    taxExpiry: '31/12/2570',
    inspectionExpiry: '20/08/2570',
    gasCertExpiry: '18/09/2570',
    gasTankExpiry: '12/03/2574',
    status: 'available',
    currentLocation: 'ลานจอด OGA สำนักงานใหญ่',
    lat: 13.7563,
    lng: 100.5018,
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'b-sample-13a',
    bookingCode: 'BK-2569-013A',
    userId: 'u-1',
    userName: 'Employee OGA',
    userDepartment: 'ฝ่ายสนับสนุน',
    vehicleId: 'v-2',
    vehicleName: 'Toyota Fortuner',
    vehiclePlate: 'ขค 5678 กทม.',
    vehicleImage: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=600&auto=format&fit=crop&q=80',
    departureDate: '13/08/2569',
    departureTime: '09:30',
    returnDate: '13/08/2569',
    returnTime: '12:30',
    destination: 'ลูกค้า / Customer Site',
    purpose: 'บริการและตรวจเช็คอุปกรณ์หน้างาน',
    passengersCount: 2,
    driverName: 'สมศักดิ์ ขับดี',
    status: 'approved',
    statusLabel: 'อนุมัติแล้ว',
    createdAt: '2026-08-12T09:00:00.000Z',
    updatedAt: '2026-08-12T10:00:00.000Z',
  },
  {
    id: 'b-sample-13b',
    bookingCode: 'BK-2569-013B',
    userId: 'u-5',
    userName: 'Employee OGA',
    userDepartment: 'ฝ่ายการเงิน',
    vehicleId: 'v-1',
    vehicleName: 'Toyota Camry',
    vehiclePlate: 'กข 1234 กทม.',
    vehicleImage: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=600&auto=format&fit=crop&q=80',
    departureDate: '13/08/2569',
    departureTime: '13:00',
    returnDate: '13/08/2569',
    returnTime: '16:30',
    destination: 'คลังสินค้า',
    purpose: 'ตรวจสอบสต็อกสินค้าประจำเดือน',
    passengersCount: 1,
    driverName: 'สมศักดิ์ ขับดี',
    status: 'approved',
    statusLabel: 'อนุมัติแล้ว',
    createdAt: '2026-08-12T14:00:00.000Z',
    updatedAt: '2026-08-12T15:00:00.000Z',
  },
  {
    id: 'b-1',
    bookingCode: 'BK-2569-005',
    userId: 'u-1',
    userName: 'สมชาย ใจดี',
    userDepartment: 'ฝ่ายสนับสนุน',
    vehicleId: 'v-1',
    vehicleName: 'Toyota Camry',
    vehiclePlate: 'กข 1234 กทม.',
    vehicleImage: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=600&auto=format&fit=crop&q=80',
    departureDate: '10/08/2569',
    departureTime: '08:00',
    returnDate: '10/08/2569',
    returnTime: '17:00',
    destination: 'บางนา',
    purpose: 'ไปพบลูกค้า OGA Partner',
    passengersCount: 1,
    driverName: 'สมศักดิ์ ขับดี',
    userSignature: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="100" height="40"><path d="M10 25 Q 30 5, 50 20 T 90 20" fill="none" stroke="%23333" stroke-width="2"/></svg>',
    status: 'pending_dept',
    statusLabel: 'รออนุมัติหัวหน้า',
    createdAt: '2026-08-10T08:00:00.000Z',
    updatedAt: '2026-08-10T08:00:00.000Z',
  },
  {
    id: 'b-2',
    bookingCode: 'BK-2026-001',
    userId: 'u-5',
    userName: 'นภาพร รักงาน',
    userDepartment: 'ฝ่ายการเงิน',
    vehicleId: 'v-1',
    vehicleName: 'Toyota Camry',
    vehiclePlate: 'กข 1234 กทม.',
    vehicleImage: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=600&auto=format&fit=crop&q=80',
    departureDate: '16/03/2569',
    departureTime: '09:00',
    returnDate: '16/03/2569',
    returnTime: '16:30',
    destination: 'กระทรวงการคลัง ถ.พระราม 6',
    purpose: 'ยื่นเอกสารภาษีและติดต่อราชการ',
    passengersCount: 2,
    driverName: 'สมศักดิ์ ขับดี',
    userSignature: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="100" height="40"><path d="M10 20 Q 40 10, 80 30" fill="none" stroke="%23333" stroke-width="2"/></svg>',
    status: 'pending_dept',
    statusLabel: 'รออนุมัติหัวหน้า',
    createdAt: '2026-03-14T09:15:00.000Z',
    updatedAt: '2026-03-14T09:15:00.000Z',
  },
  {
    id: 'b-3',
    bookingCode: 'BK-2026-002',
    userId: 'u-6',
    userName: 'ปิยะ ตั้งใจ',
    userDepartment: 'ฝ่ายพัฒนา',
    vehicleId: 'v-3',
    vehicleName: 'Honda Odyssey',
    vehiclePlate: 'วจ 9012 กทม.',
    vehicleImage: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=600&auto=format&fit=crop&q=80',
    departureDate: '17/03/2569',
    departureTime: '08:30',
    returnDate: '17/03/2569',
    returnTime: '18:00',
    destination: 'โรงแรม Centara Grand Central Plaza',
    purpose: 'จัดแสดงโซลูชัน OGA Tech Expo 2026',
    passengersCount: 4,
    driverName: 'สมศักดิ์ ขับดี',
    userSignature: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="100" height="40"><path d="M10 30 Q 50 10, 90 25" fill="none" stroke="%23333" stroke-width="2"/></svg>',
    status: 'pending_dir',
    statusLabel: 'รออนุมัติ ผอ.',
    approver1Name: 'วิภา สุขสม',
    approver1Date: '15/03/2569 10:30',
    approver1Note: 'อนุมัติให้ตามระเบียบ',
    createdAt: '2026-03-14T11:00:00.000Z',
    updatedAt: '2026-03-15T10:30:00.000Z',
  },
  {
    id: 'b-4',
    bookingCode: 'BK-2026-003',
    userId: 'u-5',
    userName: 'นภาพร รักงาน',
    userDepartment: 'ฝ่ายการเงิน',
    vehicleId: 'v-2',
    vehicleName: 'Toyota Fortuner',
    vehiclePlate: 'คง 5678 กทม.',
    vehicleImage: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=600&auto=format&fit=crop&q=80',
    departureDate: '15/03/2569',
    departureTime: '08:00',
    returnDate: '15/03/2569',
    returnTime: '17:30',
    destination: 'จ.ปทุมธานี',
    purpose: 'ตรวจนับสต็อกสินค้าคลัง OGA คลองหลวง',
    passengersCount: 3,
    driverName: 'สมศักดิ์ ขับดี',
    userSignature: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="100" height="40"><path d="M10 15 Q 30 35, 80 15" fill="none" stroke="%23333" stroke-width="2"/></svg>',
    status: 'in_progress',
    statusLabel: 'กำลังเดินทาง',
    approver1Name: 'วิภา สุขสม',
    approver1Date: '14/03/2569 14:00',
    approver1Note: 'อนุมัติ',
    approver2Name: 'ประยุทธ์ เจริญสุข',
    approver2Date: '14/03/2569 16:30',
    approver2Note: 'อนุมัติ เดินทางปลอดภัย',
    startMileage: 78540,
    createdAt: '2026-03-14T08:00:00.000Z',
    updatedAt: '2026-03-15T08:00:00.000Z',
  },
];

export const INITIAL_MAINTENANCE: MaintenanceItem[] = [
  {
    id: 'm-1',
    vehicleId: 'v-1',
    vehicleName: 'Toyota Camry',
    vehiclePlate: 'กข 1234 กทม.',
    type: 'gas_cert',
    typeLabel: 'ตรวจสภาพ & ใบรับรองวิศวกรแก๊สประจำปี',
    category: 'gas_system',
    categoryLabel: 'ระบบแก๊ส 2 เชื้อเพลิง (Dual Fuel)',
    serviceDate: '15/10/2568',
    expiryDate: '15/10/2569',
    daysRemaining: 61,
    status: 'warning',
    mileageRecord: 38200,
    nextMileage: 50000,
    serviceCenter: 'ศูนย์บริการติดตั้งแก๊สมาตรฐาน บิ๊กการาจ พระราม 3',
    invoiceNo: 'GAS-2568-084',
    cost: 800,
    note: 'ตรวจระบบแก๊ส LPG ครบวงจร ผ่านการรับรองจากวิศวกร กรมการขนส่งฯ',
    actionStatus: 'completed',
    gasCertNo: 'ENG-GAS-68/1092',
    performedBy: 'นายพิทักษ์ จุ้ยสัมพันธ์',
  },
  {
    id: 'm-2',
    vehicleId: 'v-1',
    vehicleName: 'Toyota Camry',
    vehiclePlate: 'กข 1234 กทม.',
    type: 'act',
    typeLabel: 'พ.ร.บ. คุ้มครองผู้ประสบภัยจากรถ',
    category: 'documents',
    categoryLabel: 'ภาษี / พ.ร.บ. / ประกันภัย',
    serviceDate: '15/08/2568',
    expiryDate: '15/08/2569',
    daysRemaining: 0,
    status: 'critical',
    mileageRecord: 42000,
    serviceCenter: 'วิริยะประกันภัย สาขาสาทร',
    invoiceNo: 'ACT-68-9841',
    cost: 645,
    note: 'ถึงกำหนดต่ออายุ พ.ร.บ. ด่วน เพื่อใช้ยื่นชำระภาษีประจำปี',
    actionStatus: 'pending',
    performedBy: 'แอดมิน OGA Fleet',
  },
  {
    id: 'm-3',
    vehicleId: 'v-5',
    vehicleName: 'Toyota Vios 2108',
    vehiclePlate: 'ฆค 2108 กทม.',
    type: 'gas_filter_vapor',
    typeLabel: 'เปลี่ยนกรองแก๊สไอ (Gas Vapor Filter)',
    category: 'gas_system',
    categoryLabel: 'ระบบแก๊ส 2 เชื้อเพลิง (Dual Fuel)',
    serviceDate: '18/02/2569',
    expiryDate: '18/08/2569',
    daysRemaining: 3,
    status: 'critical',
    mileageRecord: 120000,
    nextMileage: 140000,
    serviceCenter: 'อู่ช่างเล็ก แก๊สเซอร์วิส บางนา',
    invoiceNo: 'INV-GAS-901',
    cost: 650,
    note: 'เปลี่ยนกรองแก๊สไอแท้ 12mm พร้อมเช็คท่อแก๊สไม่พบรั่วซึม',
    actionStatus: 'completed',
    performedBy: 'นายพิทักษ์ จุ้ยสัมพันธ์',
  },
  {
    id: 'm-4',
    vehicleId: 'v-3',
    vehicleName: 'Toyota Vios 4470',
    vehiclePlate: 'ฆพ 4470 กทม.',
    type: 'oil_change',
    typeLabel: 'เปลี่ยนถ่ายน้ำมันเครื่องสังเคราะห์ & ไส้กรอง (เกรดรถแก๊ส)',
    category: 'fluids_engine',
    categoryLabel: 'เครื่องยนต์ & ของเหลว',
    serviceDate: '10/03/2569',
    expiryDate: '10/09/2569',
    daysRemaining: 26,
    status: 'warning',
    mileageRecord: 25000,
    nextMileage: 35000,
    serviceCenter: 'ศูนย์โตโยต้า เค.มอเตอร์ส สาทร',
    invoiceNo: 'TY-2569-4501',
    cost: 2400,
    note: 'ใช้น้ำมันเครื่อง Fully Synthetic 5W-30 รองรับเครื่องยนต์ 2 เชื้อเพลิง',
    actionStatus: 'completed',
    performedBy: 'นางศิรัลรัตน์ คงรักษา',
  },
  {
    id: 'm-5',
    vehicleId: 'v-2',
    vehicleName: 'Toyota Fortuner',
    vehiclePlate: 'ขค 5678 กทม.',
    type: 'tire_rotation',
    typeLabel: 'สลับยาง ถ่วงล้อ และตั้งศูนย์ล้อ',
    category: 'brakes_tires_suspension',
    categoryLabel: 'เบรก / ยาง / ช่วงล่าง',
    serviceDate: '20/05/2569',
    expiryDate: '20/11/2569',
    daysRemaining: 97,
    status: 'normal',
    mileageRecord: 75000,
    nextMileage: 85000,
    serviceCenter: 'บี-ควิก สาขาพระราม 3',
    invoiceNo: 'BQ-78401',
    cost: 800,
    note: 'สลับยางหน้า-หลัง ถ่วงล้อ 4 ล้อ ตรวจลมยางไนโตรเจน',
    actionStatus: 'completed',
    performedBy: 'นายเกรียงไกร ญาณเตชัส',
  },
  {
    id: 'm-6',
    vehicleId: 'v-5',
    vehicleName: 'Toyota Vios 2108',
    vehiclePlate: 'ฆค 2108 กทม.',
    type: 'gas_tank',
    typeLabel: 'ตรวจเช็คถังแก๊ส & วาล์วนิรภัย (Multivalve / อายุถัง)',
    category: 'gas_system',
    categoryLabel: 'ระบบแก๊ส 2 เชื้อเพลิง (Dual Fuel)',
    serviceDate: '12/03/2568',
    expiryDate: '12/03/2574',
    daysRemaining: 1305,
    status: 'normal',
    mileageRecord: 110000,
    serviceCenter: 'ศูนย์ทดสอบถังแก๊ส กรมการขนส่งทางบก',
    invoiceNo: 'TK-68-109',
    cost: 1200,
    note: 'ถังแก๊สโดนัท 42 ลิตร ผลทดสอบแรงดันสมบูรณ์ 100% หมดอายุปี 2574',
    actionStatus: 'completed',
    gasCertNo: 'TNK-LPG-5491',
    performedBy: 'นายพิทักษ์ จุ้ยสัมพันธ์',
  },
  {
    id: 'm-7',
    vehicleId: 'v-4',
    vehicleName: 'Toyota Hilux Revo',
    vehiclePlate: 'ฉช 3344 กทม.',
    type: 'brake_service',
    typeLabel: 'ตรวจเช็คเปลี่ยนผ้าเบรก จานเบรก และน้ำมันเบรก',
    category: 'brakes_tires_suspension',
    categoryLabel: 'เบรก / ยาง / ช่วงล่าง',
    serviceDate: '25/07/2569',
    expiryDate: '25/01/2570',
    daysRemaining: 163,
    status: 'normal',
    mileageRecord: 90000,
    nextMileage: 110000,
    serviceCenter: 'ศูนย์บริการโตโยต้า สาทร',
    invoiceNo: 'TY-2569-8912',
    cost: 3200,
    note: 'เปลี่ยนผ้าเบรกหน้าแท้ เจียรจานเบรก และไล่ลมน้ำมันเบรก DOT4',
    actionStatus: 'completed',
    performedBy: 'นายศุภณัฐ ทรัพย์อินทร์',
  },
  {
    id: 'm-8',
    vehicleId: 'v-1',
    vehicleName: 'Toyota Camry',
    vehiclePlate: 'กข 1234 กทม.',
    type: 'tax',
    typeLabel: 'ภาษีประจำปี (ป้ายวงกลม)',
    category: 'documents',
    categoryLabel: 'ภาษี / พ.ร.บ. / ประกันภัย',
    serviceDate: '31/12/2568',
    expiryDate: '31/12/2569',
    daysRemaining: 138,
    status: 'normal',
    cost: 1600,
    note: 'ชำระภาษีรถยนต์ประจำปี ณ กรมการขนส่งทางบก จตุจักร',
    actionStatus: 'completed',
    performedBy: 'แอดมิน OGA Fleet',
  },
  {
    id: 'm-9',
    vehicleId: 'v-3',
    vehicleName: 'Toyota Vios 4470',
    vehiclePlate: 'ฆพ 4470 กทม.',
    type: 'spark_plugs',
    typeLabel: 'เปลี่ยนหัวเทียน (อิริเดียมสำหรับรถ 2 เชื้อเพลิง)',
    category: 'fluids_engine',
    categoryLabel: 'เครื่องยนต์ & ของเหลว',
    serviceDate: '15/01/2569',
    expiryDate: '15/01/2570',
    daysRemaining: 153,
    status: 'normal',
    mileageRecord: 30000,
    nextMileage: 70000,
    serviceCenter: 'ศูนย์โตโยต้า เค.มอเตอร์ส',
    invoiceNo: 'SP-9912',
    cost: 1600,
    note: 'เปลี่ยนหัวเทียน NGK Laser Iridium 4 หัว สตาร์ทติดง่าย อัตราเร่งดี',
    actionStatus: 'completed',
    performedBy: 'นางศิรัลรัตน์ คงรักษา',
  },
  {
    id: 'm-10',
    vehicleId: 'v-5',
    vehicleName: 'Toyota Vios 2108',
    vehiclePlate: 'ฆค 2108 กทม.',
    type: 'gas_injectors',
    typeLabel: 'ปรับจูนกล่อง ECU แก๊ส & เช็คหัวฉีดแก๊ส',
    category: 'gas_system',
    categoryLabel: 'ระบบแก๊ส 2 เชื้อเพลิง (Dual Fuel)',
    serviceDate: '19/08/2569',
    expiryDate: '19/02/2570',
    daysRemaining: 188,
    status: 'normal',
    mileageRecord: 124300,
    serviceCenter: 'อู่ช่างเล็ก แก๊สเซอร์วิส บางนา',
    invoiceNo: 'CAL-2569-88',
    cost: 1200,
    note: 'ปรับจูนแก๊สผ่าน OBD กราฟเนียน อัตราเร่งสมูท สลับระบบน้ำมัน-แก๊สไร้รอยต่อ',
    actionStatus: 'completed',
    performedBy: 'นายพิทักษ์ จุ้ยสัมพันธ์',
  },
];

export const INITIAL_REPAIR_ORDERS: RepairOrder[] = [
  {
    id: 'ro-1',
    orderCode: 'WO-2569-001',
    vehicleId: 'v-4',
    vehicleName: 'Toyota Hilux Revo',
    vehiclePlate: 'ฉช 3344 กทม.',
    vehicleMileage: 91200,
    repairCategory: 'brake_suspension',
    repairCategoryLabel: 'เบรก / ช่วงล่าง / ยาง',
    issueDescription: 'ระบบเบรกหน้ามีเสียงดังผิดปกติขณะชะลอความเร็ว และระยะเบรกยาวกว่าปกติ ต้องการตรวจเช็คผ้าเบรกและจานเบรกด่วน',
    repairDetails: 'เปลี่ยนผ้าเบรกหน้าแท้ Toyota, เจียรจานเบรกคู่หน้า, เปลี่ยนถ่ายน้ำมันเบรก DOT4 เต็มระบบ และตรวจสอบลูกปืนล้อหน้า',
    partsReplaced: 'ผ้าเบรกหน้าแท้ (04465-0K360), น้ำมันเบรก DOT4 1L, น้ำยาทำความสะอาดเบรก',
    startDate: '14/08/2569 08:30',
    estimatedReturnDate: '18/08/2569 16:30',
    actualReturnDate: '',
    garageName: 'ศูนย์บริการโตโยต้า เค.มอเตอร์ส สาขาสาทร',
    garageContact: '02-678-9000 (ช่างสมศักดิ์ ต่อ 104)',
    technicianName: 'ช่างสมศักดิ์ ชำนาญการ',
    invoiceNo: 'TY-WO-690814',
    cost: 4850,
    paymentStatus: 'company_billing',
    requesterName: 'นายพิทักษ์ จุ้ยสัมพันธ์',
    requesterDepartment: 'ฝ่ายเทคโนโลยีและยานพาหนะ',
    status: 'in_progress',
    note: 'รถอยู่ระหว่างรอรับอะไหล่และทดสอบเบรก กำหนดส่งมอบวันที่ 18 ส.ค. 2569',
    createdAt: '2026-08-14T08:30:00.000Z',
    updatedAt: '2026-08-14T09:15:00.000Z',
  },
  {
    id: 'ro-2',
    orderCode: 'WO-2569-002',
    vehicleId: 'v-5',
    vehicleName: 'Toyota Vios 2108',
    vehiclePlate: 'ฆค 2108 กทม.',
    vehicleMileage: 124300,
    repairCategory: 'gas_system',
    repairCategoryLabel: 'ระบบแก๊ส LPG / NGV (Dual Fuel)',
    issueDescription: 'ครบกำหนดรอบเปลี่ยนกรองแก๊สไอ และรอบเครื่องยนต์เดินเบาสั่นเล็กน้อยขณะใช้เชื้อเพลิงแก๊ส LPG',
    repairDetails: 'เปลี่ยนกรองแก๊สไอแท้ 12mm, ล้างชุดปีกผีเสื้อ, ปรับจูนแมพแก๊สผ่านคอมพิวเตอร์ OBD, ทดสอบแรงดันแก๊สและเช็ครอยรั่ว 100%',
    partsReplaced: 'กรองแก๊สไอแท้ Certools 12x12mm, โอริงกรองแก๊ส, น้ำยาล้างปีกผีเสื้อ',
    startDate: '10/08/2569 09:00',
    estimatedReturnDate: '10/08/2569 17:00',
    actualReturnDate: '10/08/2569 16:45',
    garageName: 'อู่ช่างเล็ก แก๊สเซอร์วิส บางนา',
    garageContact: '081-445-6789 (ช่างเล็ก)',
    technicianName: 'ช่างเล็ก มาตรฐานวิศวกร',
    invoiceNo: 'GAS-RO-2569-089',
    cost: 1850,
    paymentStatus: 'paid',
    requesterName: 'นายพิทักษ์ จุ้ยสัมพันธ์',
    requesterDepartment: 'ฝ่ายบริการเทคโนโลยี',
    status: 'returned',
    note: 'ตรวจรับรถเรียบร้อย เครื่องเดินเรียบทั้งน้ำมันและแก๊ส ส่งคืนเข้า Fleet สำเร็จ',
    createdAt: '2026-08-10T09:00:00.000Z',
    updatedAt: '2026-08-10T16:45:00.000Z',
  },
  {
    id: 'ro-3',
    orderCode: 'WO-2569-003',
    vehicleId: 'v-2',
    vehicleName: 'Toyota Fortuner',
    vehiclePlate: 'ขค 5678 กทม.',
    vehicleMileage: 78540,
    repairCategory: 'ac_electrical',
    repairCategoryLabel: 'ระบบแอร์ & ไฟฟ้า',
    issueDescription: 'ระบบปรับอากาศไม่เย็นจัดขณะจอดรถติดไฟแดง และมีกลิ่นอับจากช่องแอร์ด้านหลัง',
    repairDetails: 'ล้างตู้แอร์แบบไมโครสโคปิก ไม่ถอดคอนโซล, อบโอโซนฆ่าเชื้อ, เติมน้ำยาแอร์ 134a และเปลี่ยนไส้กรองแอร์ป้องกัน PM2.5 คาร์บอน',
    partsReplaced: 'กรองแอร์คาร์บอนแท้ Denso, น้ำยาแอร์ R134a, น้ำมันคอมเพรสเซอร์แอร์ PAG46',
    startDate: '15/08/2569 10:00',
    estimatedReturnDate: '16/08/2569 12:00',
    actualReturnDate: '',
    garageName: 'ออโต้แอร์ เซอร์วิส สาทร-นราธิวาส',
    garageContact: '02-234-5678',
    technicianName: 'ช่างวิชัย',
    invoiceNo: 'AC-6908-152',
    cost: 2400,
    paymentStatus: 'pending',
    requesterName: 'นายดำรงค์ แสนสุข',
    requesterDepartment: 'ฝ่ายพัฒนาธุรกิจ',
    status: 'completed',
    note: 'ซ่อมเสร็จเรียบร้อย ทดสอบความเย็นช่องแอร์ 4.8°C พร้อมส่งมอบรับรถคืน',
    createdAt: '2026-08-15T10:00:00.000Z',
    updatedAt: '2026-08-16T11:00:00.000Z',
  },
  {
    id: 'ro-4',
    orderCode: 'WO-2569-004',
    vehicleId: 'v-1',
    vehicleName: 'Toyota Camry',
    vehiclePlate: 'กข 1234 กทม.',
    vehicleMileage: 45230,
    repairCategory: 'periodic_service',
    repairCategoryLabel: 'เช็คระยะ / เปลี่ยนถ่ายของเหลว',
    issueDescription: 'นัดหมายเช็คระยะ 50,000 กม. เปลี่ยนถ่ายน้ำมันเครื่องสังเคราะห์แท้ ตรวจสภาพทั่วไป 24 รายการ',
    repairDetails: 'ถ่ายน้ำมันเครื่องสังเคราะห์แท้ 5W-30, เปลี่ยนไส้กรองน้ำมันเครื่อง, สลับยาง-ถ่วงล้อ, ตรวจเช็คระดับของเหลว หม้อน้ำ น้ำมันเบรก',
    partsReplaced: 'น้ำมันเครื่องเกรดพรีเมียม 4.5L, ไส้กรองแท้, แหวนรองอ่าง',
    startDate: '20/08/2569 09:00',
    estimatedReturnDate: '20/08/2569 16:00',
    actualReturnDate: '',
    garageName: 'ศูนย์บริการโตโยต้า เค.มอเตอร์ส สาขาสาทร',
    garageContact: '02-678-9000',
    technicianName: 'ฝ่ายบริการเช็คระยะ',
    cost: 3200,
    paymentStatus: 'company_billing',
    requesterName: 'นางศิรัลรัตน์ คงรักษา',
    requesterDepartment: 'ฝ่ายธุรการ & ยานพาหนะ',
    status: 'pending',
    note: 'เปิดใบสั่งซ่อมล่วงหน้าตามรอบเช็คระยะ รอนำรถเข้าศูนย์ตามนัด',
    createdAt: '2026-08-16T08:00:00.000Z',
    updatedAt: '2026-08-16T08:00:00.000Z',
  },
];

export const INITIAL_GPS_TRACK: GPSTrackingInfo = {
  vehicleId: 'v-2',
  vehicleName: 'Toyota Fortuner',
  plate: 'คง 5678 กทม.',
  driver: 'สมศักดิ์ ขับดี',
  destination: 'จ.ปทุมธานี',
  origin: 'สำนักงานกลาง กรุงเทพฯ (OGA HQ)',
  currentAddress: 'ถ.พหลโยธิน ช่วงรังสิต-คลองหลวง',
  speed: 62,
  progress: 48,
  updateTime: '09:09:04',
  isLive: true,
  coordinates: { lat: 13.9880, lng: 100.6170 },
  path: [
    { lat: 13.7563, lng: 100.5018 },
    { lat: 13.8120, lng: 100.5530 },
    { lat: 13.8850, lng: 100.5840 },
    { lat: 13.9880, lng: 100.6170 },
    { lat: 14.0205, lng: 100.5284 }
  ]
};
